// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD9g9Hen3RH1g10Xq7_dUewazbeoe5UBTw',
    appId: '1:458754046449:web:31273cbc36a6aa6016ac50',
    messagingSenderId: '458754046449',
    projectId: 'teste-app-e3f6e',
    authDomain: 'teste-app-e3f6e.firebaseapp.com',
    storageBucket: 'teste-app-e3f6e.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBDzOeLn1LoGgjmWu2efF-gaSc3IqBp-zI',
    appId: '1:458754046449:android:49fb795fd5773c7016ac50',
    messagingSenderId: '458754046449',
    projectId: 'teste-app-e3f6e',
    storageBucket: 'teste-app-e3f6e.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCU_pwHeOl4TrynFgq_VFzJfLBsSk5LCqs',
    appId: '1:458754046449:ios:a022def39847b22716ac50',
    messagingSenderId: '458754046449',
    projectId: 'teste-app-e3f6e',
    storageBucket: 'teste-app-e3f6e.appspot.com',
    iosBundleId: 'com.example.diarioDeViagens',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCU_pwHeOl4TrynFgq_VFzJfLBsSk5LCqs',
    appId: '1:458754046449:ios:a022def39847b22716ac50',
    messagingSenderId: '458754046449',
    projectId: 'teste-app-e3f6e',
    storageBucket: 'teste-app-e3f6e.appspot.com',
    iosBundleId: 'com.example.diarioDeViagens',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD9g9Hen3RH1g10Xq7_dUewazbeoe5UBTw',
    appId: '1:458754046449:web:f09688b58fe2fb1716ac50',
    messagingSenderId: '458754046449',
    projectId: 'teste-app-e3f6e',
    authDomain: 'teste-app-e3f6e.firebaseapp.com',
    storageBucket: 'teste-app-e3f6e.appspot.com',
  );

}